---
out_dir: results
metric_best: mae
num_workers: 4
wandb:
  use: True
  name: test
  project: test-runs
  entity: ts-forecasting
dataset:
  format: PyG-TUDataset
  name: IMDB-BINARY
  task: graph
  # task_type: classification
  split_mode: cv-stratifiedkfold-5
  split_dir: splits
train:
  mode: copt
  task: maxcut
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: gnn
  loss_fun: maxcut_loss
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: copt_inductive_node
  layers_pre_mp: 1
  layers_mp: 5
  layers_post_mp: 1
  dim_inner: 300
  layer_type: hybridconv
  stage_type: skipsum
  batchnorm: true
  act: relu
  dropout: 0.3
  agg: mean
  normalize_adj: false
optim:
  base_lr: 0.003
  max_epoch: 100
  optimizer: adamW
  weight_decay: 1e-5
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
