# Configuration scaffold

constants:
  seed: 0
  device: &device cuda # cpu or cuda
  data_dir: &data_dir /home/mila/f/frederik.wenkel/scratch/data/copt/
  save_dir: &save_dir ./results/
  wandb:
    name: test-pyg
    project: copt
    entity: wenkelf

datamodule:
  task: &task maxclique
  data_dir: *data_dir
  regenerate: false
  backend: pyg
  data_kwargs:
    from_existing: collab
    supp_matrices: ["edge_index"]
  feat_kwargs:
    degree:
      type: deg
      level: node
      log_transform: true
    eccentricity:
      type: ecc
      level: node
    cluster_coefficent:
      type: clu
      level: node
    triangle_count:
      type: tri
      level: node
    constant:
      type: const
      level: node
      norm: true
  train_ds_kwargs:
    frac: 0.80
    label: false
  valid_ds_kwargs:
    frac: 0.10
    label: true
  test_ds_kwargs:
    frac: 0.10
    label: true
  batch_size_train: 256
  batch_size_valid: 1024

architecture:
  task: *task
  gnn_kwargs:
    gcn:
      type: pyg:gcn
      hidden_dim: 32
      num_layers: 4
      output_dim: 1
      last_activation: none
  head_kwargs: null
    # hidden_dim: 32
    # num_layers: 2
    # output_dim: 1
    # last_activation: none
  loss_kwargs:
    beta: 0.1
  eval_kwargs:
    mc_ratio:
      dec_length: 100

training:
  optimizer_kwargs:
    type: adam
    lr: 0.0005
    weight_decay: 0.0005
  scheduler_kwargs:
    step_size: 300
    gamma: 0.1
  train_kwargs:
    accelerator: *device
    min_epochs: 2
    max_epochs: 50
    check_val_every_n_epoch: 1
    precision: 32-true
    # stopping_patience: 10
    # valid_interval: 2
    # grad: false
    # output_model: best # best or last
    # save_dir: *save_dir

    

