# Configuration scaffold

constants:
  seed: 0
  device: &device cpu # cpu or cuda
  data_dir: &data_dir /home/mila/f/frederik.wenkel/scratch/data/copt/
  save_dir: &save_dir ./results/
  wandb:
    name: test
    project: combopt
    entity: wenkelf

datamodule:
  task: &task maxclique
  data_dir: *data_dir
  regenerate: false
  data_kwargs:
    from_existing: imdb
    supp_matrices: ["gcn"]
  feat_kwargs:
    degree:
      type: deg
      level: node
      log_transform: true
    eccentricity:
      type: ecc
      level: node
    cluster_coefficent:
      type: clu
      level: node
    triangle_count:
      type: tri
      level: node
    constant:
      type: const
      level: node
      norm: true
  train_ds_kwargs:
    frac: 0.9
    label: false
  valid_ds_kwargs:
    frac: 0.05
    label: true
  test_ds_kwargs:
    frac: 0.05
    label: true
  batch_size_train: 256
  batch_size_valid: 256

architecture:
  task: *task
  gnn_kwargs:
    gcn:
      type: gcn
      output_dim: 1
      hidden_dim: 64
      num_layers: 4
  head_kwargs:
    pool: none
    type: mlp
    hidden_dims: [16]
    out_dim: 1
  loss_kwargs: null
    beta: 0.1
  eval_kwargs: null
    mc_ratio:
      dec_length: 100

training:
  optimizer_kwargs:
    type: adam
    lr: 0.001
    weight_decay: 0.0005
  scheduler_kwargs:
    step_size: 100
    gamma: 0.1
  train_kwargs:
    accelerator: *device
    min_epochs: 2
    max_epochs: 100
    check_val_every_n_epoch: 1
    precision: 32-true
    # stopping_patience: 10
    # valid_interval: 2
    # grad: false
    # output_model: best # best or last
    # save_dir: *save_dir

    

