---
out_dir: results
metric_best: mae
num_workers: 4
wandb:
  use: True
  name: test
  project: copt-maxcut-ba-small
  entity: guy-wolf
dataset:
  format: ba
  name: small
  task: graph
  # task_type: classification
  split_mode: random
  split_dir: splits
  node_encoder: false
  node_encoder_name: RWSE
  graph_stats: ['degree', 'eccentricity', 'cluster_coefficient', 'triangle_count']
  multiprocessing: true
  label: false
posenc_LapPE:
  enable: false
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 4
    skip_zero_freq: true
    eigvec_abs: true
  model: DeepSet
  dim_pe: 32
  layers: 2
  n_heads: 4  # Only used when `posenc.model: Transformer`
  raw_norm_type: none
posenc_RWSE:
  enable: false
  kernel:
    times_func: range(2,22)  # if no self-loop, then RWSE1 will be all zeros
  model: Linear
  dim_pe: 32
  raw_norm_type: BatchNorm
posenc_GraphStats:
  enable: false
  model: Linear
  dim_pe: 32
  raw_norm_type: none
posenc_GPSE:
  enable: false
posenc_NormalRE:
  enable: false
  dim_pe: 16
randenc_DiracRE:
  enable: true
train:
  mode: copt
  # compile: True
  task: maxcut
  batch_size: 256
  eval_period: 1
  ckpt_period: 100
  ckpt_best: true
model:
  type: erdos_anneal
  loss_fun: maxcut_loss
  edge_decoding: dot
  graph_pooling: mean
gnn:
  layers_mp: 4
  dim_inner: 64
  batchnorm: true
  graphnorm: false
  l2norm: false
  norm_by_graph: true
  act: lrelu_001
  last_act: null
  last_norm: minmax
  dropout: 0.3
  agg: mean
  normalize_adj: false
optim:
  base_lr: 0.001
  max_epoch: 300
  optimizer: adam
  weight_decay: 1e-5
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
  entropy:
    enable: false
    scheduler: linear-energy
    base_temp: 100.0
    min_temp: 0.001