---
out_dir: results
metric_best: mae
num_workers: 4
wandb:
  use: True
  name: test
  project: copt-maxcut-ba-large
  entity: guy-wolf
dataset:
  format: ba
  name: large
  task: graph
  # task_type: classification
  split_mode: random
  split_dir: splits
  node_encoder: false
  node_encoder_name: RWSE
  graph_stats: ['degree', 'eccentricity', 'cluster_coefficient', 'triangle_count']
  multiprocessing: true
  label: false
randenc_DiracRE:
  enable: true
train:
  mode: copt
  # compile: True
  task: maxcut
  batch_size: 256
  eval_period: 1
  ckpt_period: 100
  ckpt_best: true
model:
  type: gnn
  loss_fun: maxcut_loss
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: copt_inductive_node
  layers_pre_mp: 4
  layers_mp: 16
  layers_post_mp: 1
  dim_inner: 32
  layer_type: erdosginconv
  stage_type: skipsum_concat_erdos
  batchnorm: true
  graphnorm: false
  l2norm: true
  gsn: false
  act: lrelu_001
  last_act: sigmoid
  dropout: 0.3
  agg: mean
  normalize_adj: false
optim:
  base_lr: 0.001
  max_epoch: 400
  optimizer: adam
  weight_decay: 1e-5
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
  entropy:
    enable: false
    scheduler: linear-energy
    base_temp: 100.0
    min_temp: 0.001