---
out_dir: results
metric_best: mae
num_workers: 4
dim_out: 1
wandb:
  use: True
  name: test
  project: copt-mds-ba-small
  entity: guy-wolf
dataset:
  format: ba
  name: small
  task: graph
  # task_type: classification
  split_mode: cv-kfold-5
  split_dir: splits
  node_encoder: true
  node_encoder_name: GraphStats
  graph_stats: ['degree', 'eccentricity', 'cluster_coefficient', 'triangle_count']
  multiprocessing: true
  label: false
posenc_LapPE:
  enable: false
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 4
    skip_zero_freq: true
    eigvec_abs: true
  model: DeepSet
  dim_pe: 32
  layers: 2
  n_heads: 4  # Only used when `posenc.model: Transformer`
  raw_norm_type: none
posenc_RWSE:
  enable: false
  kernel:
    times_func: range(2,22)  # if no self-loop, then RWSE1 will be all zeros
  model: Linear
  dim_pe: 32
  raw_norm_type: BatchNorm
posenc_GraphStats:
  enable: true
  model: Linear
  dim_pe: 256
  raw_norm_type: none
posenc_GPSE:
  enable: false
posenc_NormalRE:
  enable: false
  dim_pe: 16
train:
  mode: copt
  # compile: True
  task: mds
  batch_size: 256
  val_period: 5
  ckpt_period: 100
  ckpt_best: true
model:
  type: gnn
  loss_fun: mds_loss
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: copt_inductive_node
  layers_pre_mp: 1
  layers_mp: 16
  layers_post_mp: 1
  dim_inner: 256
  layer_type: hybridconv-v2
  stage_type: skipsum
  batchnorm: true
  graphnorm: false
  l2norm: true
  norm_by_graph: false
  act: gelu
  last_act: sigmoid
  last_norm: null
  dropout: 0.3
  agg: mean
  normalize_adj: false
  hybrid:
    activation_att1: gelu
    activation_att2: gelu
    activation: gelu
  hybrid_v2:
    skip: false
optim:
  base_lr: 0.001
  max_epoch: 200
  eval_period: 5
  optimizer: adam
  weight_decay: 1e-5
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
metrics:
  mds:
    num_seeds: 10