---
out_dir: results
metric_best: mae
num_workers: 4
dim_out: 1
wandb:
  use: True
  name: test
  project: copt-mds-ba-large
  entity: guy-wolf
dataset:
  format: ba
  name: large
  task: graph
  # task_type: classification
  split_mode: random
  split_dir: splits
  node_encoder: false
  node_encoder_name: GraphStats
  graph_stats: ['degree', 'eccentricity', 'cluster_coefficient', 'triangle_count']
  multiprocessing: true
  label: false
randenc_DiracRE:
  enable: true
train:
  mode: copt
  # compile: True
  task: mds
  batch_size: 256
  val_period: 5
  ckpt_period: 100
  ckpt_best: true
model:
  type: gnn
  loss_fun: mds_loss
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: copt_inductive_node
  layers_pre_mp: 1
  layers_mp: 16
  layers_post_mp: 1
  dim_inner: 256
  layer_type: erdosginconv
  stage_type: skipsum_concat
  batchnorm: true
  graphnorm: false
  l2norm: true
  gsn: true
  act: lrelu_001
  last_act: sigmoid
  last_norm: null
  dropout: 0.3
  agg: mean
  normalize_adj: false
optim:
  base_lr: 0.001
  max_epoch: 200
  eval_period: 5
  optimizer: adam
  weight_decay: 1e-5
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
  entropy:
    enable: false
    scheduler: linear-energy
    base_temp: 1.0
    min_temp: 0.001
metrics:
  mds:
    num_seeds: 1